# 宿題  
  
MNIST(8x8 pixels)のデータセットを使って、  
RandomForest分類器の他に２種類、分類器を用意して学習させ、  
それぞれの学習済みモデルの精度を比較し、  
文字認識の観点から精度や モデルが予測する結果について考察しなさい。  
評価対象はaccuracy_scoreとconfusion_matrixとします。

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits

%matplotlib inline

In [2]:
mnist = load_digits()

文字認識について調べる  
参考URLhttps://office54.net/python/ai/machine-learning-method

①ランダムフォレストhttps://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html    
・それぞれ異なったグループで学習をし、いくつかの決定木を作り、平均・多数決するhttps://qiita.com/Hawaii/items/5831e667723b66b46fba  
・ランダム性（それぞれ異なるデータを基にする、異なる説明変数を分割候補として使う）https://mathwords.net/randomforest  
https://qiita.com/mshinoda88/items/8bfe0b540b35437296bd

②ロジスティクス回帰  
・特徴量空間が線形分離可能な場合のみに高い性能を発揮する  
  
・特徴量空間  
　説明変数がある空間  
　・特徴量  
　　データのどのような特徴に着目すべきか  
  　分析対象データの中の予測の手掛かりとなる変数  
    Excelなどの一つの列が特徴量になる
    
特徴量空間とは目的変数を説明するためのデータが存在する空間のことを言います。
目的変数のとある１点は説明変数の特徴量空間の次元のそれぞれ１点の結果として現れるものであり、
特徴量空間の１点と目的変数の１点はつながっているものと考えるのがポイントです。

今回の画像で言えば、64次元の各次元（各ピクセル）のそれぞれの値（色味：グレースケールならば8bitで0-255階調）のもと、
人間が認識できる文字（目的変数の値）と紐づくと考えます。

ベクトルとは、特徴量空間の各次元の１点を集約して表現したものであり、
データセット言えば行に相当するものです。

まとめると（繰り返しにはなりますが）、**目的変数の点が64次元の数値で表され、各次元に存在する数値の組み合わせがベクトルであり、
そのベクトルがあるときに目的変数である人間が認識できる数値情報と紐づく**と考えばＯＫです。

参考URLhttps://qiita.com/0NE_shoT_/items/b702ab482466df6e5569  
  
線形分離可能  
https://qiita.com/forusufia/items/53de18be0e07b258fc76  
https://pictblog.com/ai-bunrui-9  

のちに調べて分かったhttps://aidemy.net/magazine/655/

③K近傍法（ケイきんぼうほう）  
https://toukei-lab.com/%EF%BD%8B%E8%BF%91%E5%82%8D%E6%B3%95

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
import seaborn as sns

In [4]:
mnist.keys()

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])

In [5]:
x = mnist["data"]

In [6]:
x

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [7]:
y = mnist["target"]

In [8]:
y

array([0, 1, 2, ..., 8, 9, 8])

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

**①ランダムフォレスト**

In [10]:
reg = RandomForestClassifier()

In [11]:
reg.fit(x_train, y_train)

RandomForestClassifier()

In [12]:
y_pred_reg = reg.predict(x_test)

In [13]:
accuracy_score(y_test, y_pred_reg)

0.9722222222222222

In [14]:
confusion_matrix(y_test, y_pred_reg)

array([[34,  0,  0,  0,  1,  0,  0,  0,  0,  0],
       [ 0, 45,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 33,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 36,  0,  0,  0,  1,  2,  1],
       [ 0,  0,  0,  0, 43,  0,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0, 34,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0, 28,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 34,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  0,  0, 28,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  1,  0, 35]], dtype=int64)

In [25]:
from sklearn.metrics import multilabel_confusion_matrix
# https://splunktool.com/multiclass-multilabel-confusion-matrix-with-sklearn

In [23]:
multilabel_confusion_matrix(y_test, y_pred_reg)

array([[[325,   0],
        [  1,  34]],

       [[314,   1],
        [  0,  45]],

       [[327,   0],
        [  0,  33]],

       [[320,   0],
        [  4,  36]],

       [[314,   2],
        [  1,  43]],

       [[326,   0],
        [  0,  34]],

       [[331,   0],
        [  1,  28]],

       [[324,   2],
        [  0,  34]],

       [[328,   2],
        [  2,  28]],

       [[321,   3],
        [  1,  35]]], dtype=int64)

In [143]:
reg1 = RandomForestClassifier()

In [144]:
reg1.fit(x_train, y_train)

RandomForestClassifier()

In [145]:
y_pred_reg1 = reg1.predict(x_test)

In [146]:
accuracy_score(y_test, y_pred_reg1)

0.9916666666666667

In [147]:
confusion_matrix(y_test, y_pred_reg1)

array([[36,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 34,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 39,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 41,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 39,  0,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0, 39,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 35,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 29,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0, 33,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  1, 32]], dtype=int64)

In [148]:
reg2 = RandomForestClassifier()

In [149]:
reg2.fit(x_train, y_train)

RandomForestClassifier()

In [150]:
y_pred_reg2 = reg2.predict(x_test)

In [151]:
accuracy_score(y_test, y_pred_reg2)

0.9888888888888889

In [152]:
confusion_matrix(y_test, y_pred_reg2)

array([[36,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 34,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 39,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 41,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 39,  0,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0, 39,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 35,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 29,  0,  0],
       [ 0,  1,  1,  0,  0,  0,  0,  0, 32,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0,  0, 32]], dtype=int64)

**②ロジスティクス回帰**

In [80]:
lr = LogisticRegression(max_iter=5000)

In [81]:
lr.fit(x_train, y_train)

LogisticRegression(max_iter=5000)

In [82]:
y_pred_lr = lr.predict(x_test)

In [98]:
accuracy_score(y_test, y_pred_lr)

0.9694444444444444

In [99]:
confusion_matrix(y_test, y_pred_lr)

array([[36,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 34,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1, 38,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 40,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 40,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  1, 36,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 35,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 29,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0, 32,  0],
       [ 0,  0,  0,  1,  0,  1,  0,  0,  2, 29]], dtype=int64)

**③K近傍法（ケイきんぼうほう）**

In [84]:
# n_neighborn = 5(default)
k = KNeighborsClassifier()

In [85]:
k.fit(x_train, y_train)

KNeighborsClassifier()

In [86]:
y_pred_k = k.predict(x_test)

In [101]:
accuracy_score(y_test, y_pred_k)

0.9861111111111112

In [93]:
confusion_matrix(y_test, y_pred_k)

array([[36,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 34,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 39,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 40,  0,  0,  0,  1,  0,  0],
       [ 0,  0,  0,  0, 40,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 39,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 35,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 29,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0, 32,  0],
       [ 0,  0,  0,  2,  0,  0,  0,  0,  0, 31]], dtype=int64)

In [154]:
k1 = KNeighborsClassifier(n_neighbors = 2)

In [155]:
k1.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=2)

In [156]:
y_pred_k1 = k1.predict(x_test)

In [157]:
accuracy_score(y_test, y_pred_k1)

0.9861111111111112

In [158]:
confusion_matrix(y_test, y_pred_k1)

array([[36,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 34,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 39,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 41,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 40,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 39,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 35,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 29,  0,  0],
       [ 0,  3,  0,  0,  0,  0,  0,  0, 31,  0],
       [ 0,  0,  0,  2,  0,  0,  0,  0,  0, 31]], dtype=int64)

In [160]:
k2 = KNeighborsClassifier(n_neighbors = 10)

In [161]:
k2.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=10)

In [162]:
y_pred_k2 = k2.predict(x_test)

In [163]:
accuracy_score(y_test, y_pred_k2)

0.9916666666666667

In [164]:
confusion_matrix(y_test, y_pred_k2)

array([[36,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 34,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 39,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 41,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 40,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 39,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 35,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 29,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0, 32,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0,  0, 32]], dtype=int64)

In [17]:
k3 = KNeighborsClassifier(n_neighbors = 100)

In [18]:
k3.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=100)

In [19]:
y_pred_k3 = k3.predict(x_test)

In [21]:
accuracy_score(y_test, y_pred_k3)

0.9111111111111111

In [22]:
confusion_matrix(y_test, y_pred_k3)

array([[35,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 29,  1,  0,  0,  0,  2,  0,  0,  1],
       [ 0,  0, 34,  0,  0,  0,  0,  2,  0,  0],
       [ 0,  0,  0, 37,  0,  0,  0,  1,  0,  0],
       [ 0,  2,  0,  0, 30,  0,  0,  5,  0,  0],
       [ 0,  0,  0,  0,  0, 33,  0,  0,  0,  4],
       [ 0,  0,  0,  0,  0,  0, 25,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 41,  0,  0],
       [ 0,  3,  0,  1,  0,  0,  0,  1, 31,  0],
       [ 0,  3,  0,  1,  1,  2,  0,  2,  0, 33]], dtype=int64)

In [34]:
# 値の関係性
df = pd.DataFrame(mnist["data"])
df.columns = mnist["feature_names"]
df

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0           0.0        0.0        5.0       13.0        9.0        1.0   
1           0.0        0.0        0.0       12.0       13.0        5.0   
2           0.0        0.0        0.0        4.0       15.0       12.0   
3           0.0        0.0        7.0       15.0       13.0        1.0   
4           0.0        0.0        0.0        1.0       11.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        0.0        4.0       10.0       13.0        6.0   
1793        0.0        0.0        6.0       16.0       13.0       11.0   
1794        0.0        0.0        1.0       11.0       15.0        1.0   
1795        0.0        0.0        2.0       10.0        7.0        0.0   
1796        0.0        0.0       10.0       14.0        8.0        1.0   

      pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
0           0.0        0.0        0.0        0.0  ...        0.0        0.0   
1           0.0        0.0        0.0        0.0  ...        0.0        0.0   
2           0.0        0.0        0.0        0.0  ...        5.0        0.0   
3           0.0        0.0        0.0        8.0  ...        9.0        0.0   
4           0.0        0.0        0.0        0.0  ...        0.0        0.0   
...         ...        ...        ...        ...  ...        ...        ...   
1792        0.0        0.0        0.0        1.0  ...        4.0        0.0   
1793        1.0        0.0        0.0        0.0  ...        1.0        0.0   
1794        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1795        0.0        0.0        0.0        0.0  ...        2.0        0.0   
1796        0.0        0.0        0.0        2.0  ...        8.0        0.0   

      pixel_7_0  pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  \
0           0.0        0.0        6.0       13.0       10.0        0.0   
1           0.0        0.0        0.0       11.0       16.0       10.0   
2           0.0        0.0        0.0        3.0       11.0       16.0   
3           0.0        0.0        7.0       13.0       13.0        9.0   
4           0.0        0.0        0.0        2.0       16.0        4.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        0.0        2.0       14.0       15.0        9.0   
1793        0.0        0.0        6.0       16.0       14.0        6.0   
1794        0.0        0.0        2.0        9.0       13.0        6.0   
1795        0.0        0.0        5.0       12.0       16.0       12.0   
1796        0.0        1.0        8.0       12.0       14.0       12.0   

      pixel_7_6  pixel_7_7  
0           0.0        0.0  
1           0.0        0.0  
2           9.0        0.0  
3           0.0        0.0  
4           0.0        0.0  
...         ...        ...  
1792        0.0        0.0  
1793        0.0        0.0  
1794        0.0        0.0  
1795        0.0        0.0  
1796        1.0        0.0  

[1797 rows x 64 columns]

In [49]:
dft = pd.DataFrame(mnist["target"])
dft.columns = ["target"]
dft

target
0          0
1          1
2          2
3          3
4          4
...      ...
1792       9
1793       0
1794       8
1795       9
1796       8

[1797 rows x 1 columns]

In [50]:
dff = pd.concat([df, dft], axis=1)
dff

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0           0.0        0.0        5.0       13.0        9.0        1.0   
1           0.0        0.0        0.0       12.0       13.0        5.0   
2           0.0        0.0        0.0        4.0       15.0       12.0   
3           0.0        0.0        7.0       15.0       13.0        1.0   
4           0.0        0.0        0.0        1.0       11.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        0.0        4.0       10.0       13.0        6.0   
1793        0.0        0.0        6.0       16.0       13.0       11.0   
1794        0.0        0.0        1.0       11.0       15.0        1.0   
1795        0.0        0.0        2.0       10.0        7.0        0.0   
1796        0.0        0.0       10.0       14.0        8.0        1.0   

      pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
0           0.0        0.0        0.0        0.0  ...        0.0        0.0   
1           0.0        0.0        0.0        0.0  ...        0.0        0.0   
2           0.0        0.0        0.0        0.0  ...        0.0        0.0   
3           0.0        0.0        0.0        8.0  ...        0.0        0.0   
4           0.0        0.0        0.0        0.0  ...        0.0        0.0   
...         ...        ...        ...        ...  ...        ...        ...   
1792        0.0        0.0        0.0        1.0  ...        0.0        0.0   
1793        1.0        0.0        0.0        0.0  ...        0.0        0.0   
1794        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1795        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1796        0.0        0.0        0.0        2.0  ...        0.0        0.0   

      pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
0           0.0        6.0       13.0       10.0        0.0        0.0   
1           0.0        0.0       11.0       16.0       10.0        0.0   
2           0.0        0.0        3.0       11.0       16.0        9.0   
3           0.0        7.0       13.0       13.0        9.0        0.0   
4           0.0        0.0        2.0       16.0        4.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        2.0       14.0       15.0        9.0        0.0   
1793        0.0        6.0       16.0       14.0        6.0        0.0   
1794        0.0        2.0        9.0       13.0        6.0        0.0   
1795        0.0        5.0       12.0       16.0       12.0        0.0   
1796        1.0        8.0       12.0       14.0       12.0        1.0   

      pixel_7_7  target  
0           0.0       0  
1           0.0       1  
2           0.0       2  
3           0.0       3  
4           0.0       4  
...         ...     ...  
1792        0.0       9  
1793        0.0       0  
1794        0.0       8  
1795        0.0       9  
1796        0.0       8  

[1797 rows x 65 columns]

In [ ]:
sns.pairplot(dff, hue='target')
# 実行結果は画像保存した→重すぎて消しました

補足情報

In [110]:
from sklearn.metrics import f1_score, recall_score, precision_score

**精度（Precision)**  
ポジティブに分類されたアイテムのうち、実際にポジティブであったアイテムの割合  

**検出率**
本来ポジティブに分類すべきアイテムを、正しくポジティブに分類できたアイテムの割合  

**F値**
精度（Precision)と検出率(Recall)を調和した値  
精度は高くても検出率の低いモデルになっていないか？、検出率は高くても精度は低くはないか？  
0が悪い、1が良い  

https://pythondatascience.plavox.info/scikit-learn/%E5%88%86%E9%A1%9E%E7%B5%90%E6%9E%9C%E3%81%AE%E3%83%A2%E3%83%87%E3%83%AB%E8%A9%95%E4%BE%A1

**多クラス分類について**  
https://di-acc2.com/analytics/ai/10801/  

マクロ平均法  
各クラス毎に評価指標（適合率・再現率など）を計算した後、  
平均を取る方法  

マイクロ平均法  
各クラスごとのTP,YN,FP,FNの値を算出した段階で集計し、  
評価指標（適合率・再現率など）算出する方法

In [130]:
# ①
precision_score(y_test, y_pred_reg, average="macro")

0.985720439691028

In [131]:
# ②
precision_score(y_test, y_pred_lr, average="macro")

0.9701167912607918

In [133]:
# ③
precision_score(y_test, y_pred_k, average="macro")

0.9863492063492064

In [134]:
# ①
recall_score(y_test, y_pred_reg, average="macro")

0.9856461675579322

In [135]:
# ②
recall_score(y_test, y_pred_lr, average="macro")

0.9693010002909572

In [138]:
# ③
recall_score(y_test, y_pred_k, average="macro")

0.9856180166079735

In [140]:
# ①
f1_score(y_test, y_pred_reg, average="macro")

0.9856108122849644

In [141]:
# ②
f1_score(y_test, y_pred_lr, average="macro")

0.9689497632621187

In [142]:
# ③
f1_score(y_test, y_pred_k, average="macro")

0.9856781810269915